networks:
  proxy:
    driver: bridge

volumes:
  mariadbdata:
    driver: local

services:
  php-fpm:
    container_name: app
    build:
      dockerfile: ./docker/php-fpm/Dockerfile
      context: .
    volumes:
      - .:/var/www/html
      - ./docker/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php-fpm/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    expose:
      - 9000
    networks:
      - proxy

  db:
    image: mariadb:10.7.1
    container_name: db # This value also serves as DB_HOST in .env database config
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd!
      MYSQL_DATABASE: crypto_portfolio
    volumes:
      - mariadbdata:/var/lib/mysql/
    networks:
      - proxy

  nginx:
    build: ./docker/nginx/
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - php-fpm
    tty: true
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    networks:
      - proxy

  openapi-builder:
    image: openapitools/openapi-generator-cli:v5.4.0
    container_name: openapi-builder
    restart: on-failure
    volumes:
      - ./docs:/local
    profiles:
      - donotstart
    command: > 
        sh -c "/usr/local/bin/docker-entrypoint.sh generate \
        -i /local/openapi.yaml \ 
        -g html2 \
        -o /local/output"